### ISSUE TITLE
Issue when restoring dump with MV

### ISSUE THREAD

**Issue by Mujjamil-K** [asotolongo/mv_stats#1]
Hi,

mv_stats extension created in PG-13 and not allow to creating the materialized view in dump. showing below error.
relation "_mv_stats" does not exist
LINE 1: INSERT INTO _mv_stats (mv_name , create_mv ) VALUES ( r.obje...

**Comment by asotolongo** [comment]
Hi @Mujjamil-K , What specific command are you running?, please share here

**Comment by asotolongo** [comment]
@Mujjamil-K please check this comment: https://github.com/asotolongo/mv_stats/issues/2#issuecomment-1959509294

**Comment by asotolongo** [comment]
Issue solved in #2
