### ISSUE TITLE
pg_restore failed to restore a MATERIALIZED VIEW because table _mv_stats doesn't exist 

### ISSUE THREAD

**Issue by sebastienruiz** [asotolongo/mv_stats#2]
Hello,

when we try to import a dump we have this error and the view can't be created because of the missing table _mv_stats.

pg_restore: from TOC entry 879; 1259 242789 MATERIALIZED VIEW pph_batch_jouve_view datahubx1
pg_restore: error: could not execute query: ERROR:  relation "_mv_stats" does not exist
LINE 1: INSERT INTO _mv_stats (mv_name , create_mv ) VALUES ( r.obje...
                    ^
QUERY:  INSERT INTO _mv_stats (mv_name , create_mv ) VALUES ( r.object_identity,now())
CONTEXT:  PL/pgSQL function public.fn_trg_mv() line 14 at SQL statement
Command was: CREATE MATERIALIZED VIEW datahubx1.pph_batch_jouve_view AS
 WITH partition AS (
         SELECT tmp.pp_id,
            tmp.pp_nom,
            tmp.pp_prenom,
….

But in fact, the table exist and the extension mv_stats is well installed (and installed before the import) : 

dpdatahubp1=> select * from mv_stats;
            mv_name             | create_mv | mod_mv | refresh_mv_last | refresh_count | refresh_mv_time_last | refresh_mv_time_total | refresh_mv_time_min | refresh_mv_time_max | reset_last
--------------------------------+-----------+--------+-----------------+---------------+----------------------+-----------------------+---------------------+---------------------+------------
 datahubp1.pph_batch_jouve_view |           |        |                 |             0 |                      | 00:00:00              |                     |                     |
 datahubp1.t9                   |           |        |                 |             0 |                      | 00:00:00              |                     |                     |
(2 rows)

dpdatahubp1=> select * from _mv_stats;
            mv_name             | create_mv | mod_mv | refresh_mv_last | refresh_count | refresh_mv_time_last | refresh_mv_time_total | refresh_mv_time_min | refresh_mv_time_max | reset_last
--------------------------------+-----------+--------+-----------------+---------------+----------------------+-----------------------+---------------------+---------------------+------------
 datahubp1.pph_batch_jouve_view |           |        |                 |             0 |                      | 00:00:00              |                     |                     |
 datahubp1.t9                   |           |        |                 |             0 |                      | 00:00:00              |                     |                     |
(2 rows)

dpdatahubp1=# \dx
                                           List of installed extensions
        Name        | Version |   Schema   |                              Description
--------------------+---------+------------+-----------------------------------------------------------------------
 adminpack          | 2.1     | pg_catalog | administrative functions for PostgreSQL
 btree_gin          | 1.3     | public     | support for indexing common datatypes in GIN
 btree_gist         | 1.5     | public     | support for indexing common datatypes in GiST
 cube               | 1.4     | public     | data type for multidimensional cubes
 dblink             | 1.2     | public     | connect to other PostgreSQL databases from within a database
 file_fdw           | 1.0     | public     | foreign-data wrapper for flat file access
 mv_stats           | 0.2.0   | public     | Extension to track statistics about materialized view in the database
 pageinspect        | 1.8     | public     | inspect the contents of database pages at a low level
 pg_buffercache     | 1.3     | public     | examine the shared buffer cache
 pg_freespacemap    | 1.2     | public     | examine the free space map (FSM)
 pg_stat_statements | 1.8     | public     | track execution statistics of all SQL statements executed
 pg_trgm            | 1.5     | public     | text similarity measurement and index searching based on trigrams
 pgcrypto           | 1.3     | public     | cryptographic functions
 pgrowlocks         | 1.2     | public     | show row-level locking information
 pgstattuple        | 1.5     | public     | show tuple-level statistics
 plpgsql            | 1.0     | pg_catalog | PL/pgSQL procedural language
 tablefunc          | 1.0     | public     | functions that manipulate whole tables, including crosstab
 unaccent           | 1.1     | public     | text search dictionary that removes accents
 uuid-ossp          | 1.1     | public     | generate universally unique identifiers (UUIDs)
 xml2               | 1.1     | public     | XPath querying and XSLT
(20 rows)

please, what can we do to resolve this error during the import ?

best regards.

**Comment by asotolongo** [comment]
@sebastienruiz thank for reporting this problem (the problem is due to this line in the backup: `SELECT pg_catalog.set_config('search_path', '', false);`), Here is a workaround :

* Filter the restore file, remove the extension creation and comment, and generate a list file to restore:

```
pg_restore -l your_dump_file | grep -v 'COMMENT - EXTENSION mv_stats' | grep -v 'EXTENSION - mv_stats' > /tmp/restore.list
```

* Restore your backup using a list file generated previously
```
pg_restore  your_dump_file  -L /tmp/restore.list
```

* Create the extension again  inside your new database
```sql
CREATE EXTENSION
```

Let me know if works for you, I tested it successfully in my local server 

Regards

**Comment by sebastienruiz** [comment]
Thanks asotolongo,
I understand the problem with the search_path, but i can't use this workaround cause this issue is on our production system.
And we have methods and scripts that we cannot modify. In any case not for this particular database which is the only one to have the mv_stat extension. Can't there be another solution?
best regards

**Comment by asotolongo** [comment]
@sebastienruiz Any solution for this will imply a change or modification of something, [this solution ](vhttps://github.com/asotolongo/mv_stats/issues/2#issuecomment-1959509294) only requires modification of the restore process, not the dump part. 

What about if ask permission to test this solution in a staging environment? 

I need to understands where you can modify or apply some modification, to try to focus on a solution

**Comment by sebastienruiz** [comment]
@asotolongo : 

thanks for the reply
I have no doubt that our solution will work. It's just that we don't want to make things like this cause mv_stats is not installed everywhere.
But i was thinking about another way : 
what abour modify mv_stats extension > disable the 3 triggers when a pg_restore is launched ?
this 3 triggers : 
dpdatahubp1-# \dy
                                                                   List of event triggers
       Name        |       Event       |  Owner   | Enabled |    Function     |                                     Tags
-------------------+-------------------+----------+---------+-----------------+------------------------------------------------------------------------------
 trg_mv_info       | ddl_command_end   | postgres | enabled | fn_trg_mv       | CREATE MATERIALIZED VIEW, ALTER MATERIALIZED VIEW, REFRESH MATERIALIZED VIEW
 trg_mv_info_drop  | sql_drop          | postgres | enabled | fn_trg_mv_drop  | DROP MATERIALIZED VIEW
 trg_mv_info_start | ddl_command_start | postgres | enabled | fn_trg_mv_start | REFRESH MATERIALIZED VIEW

and enable them after pg_restore ?
i think it's not possible but why not ;-)

regards

**Comment by asotolongo** [comment]
From my POV it not possible apply your solution about disable the triggers because  the dump file have the `CREATE EXTENSION `command not the code related to `CREATE TRIGGER`.

I updated the code of the extension in this case using the the @extschema:name@ syntax to avoid the problem with the `search_path`, please check this branch https://github.com/asotolongo/mv_stats/tree/0.3.0_version and test in your staging environment, maybe you have some use case different from my production environment (for me work the new version properly), please let me know if work for you.

Check the Update procedure: [extension](https://github.com/asotolongo/mv_stats/tree/0.3.0_version?tab=readme-ov-file#update-extension-procedure)

**Comment by sebastienruiz** [comment]
thank you very much !
i will test this new mv_stats version in a test environnement in a couple of days.
I will send you some news about it when those tests will ending.
Many thanks

**Comment by sebastienruiz** [comment]
Hi @asotolongo ,
well, all my tests are goods.
Your new version of mv_stats 0.3.0 fixes the issue with pg_restore;.
Now everything is fine during import :
.....
pg_restore: launching item 8650 MATERIALIZED VIEW DATA pph_batch_jouve_view
pg_restore: launching item 8989 MATERIALIZED VIEW DATA t9
pg_restore: creating MATERIALIZED VIEW DATA "datahubx1.pph_batch_jouve_view"
pg_restore: creating MATERIALIZED VIEW DATA "datahubx1.t9"
pg_restore: finished item 8989 MATERIALIZED VIEW DATA t9
pg_restore: finished item 8650 MATERIALIZED VIEW DATA pph_batch_jouve_view
....

Again : many thanks for your good and fast work 👍 

Best regards,
Sébastien

**Comment by asotolongo** [comment]
Thanks for your response, Glad to help

**Comment by asotolongo** [comment]
Issue solved
