### ISSUE TITLE
MV_STATS view shows duplicates

### ISSUE THREAD

**Issue by Simurgl** [asotolongo/mv_stats#5]
When doing query on mv_stats like:
SELECT
mv_stats.mv_name,
mv_stats.create_mv as create_mv
FROM mv_stats
order by mv_name;

Getting such interesting result:
          mv_name              |         create_mv
-------------------------------+----------------------------
 public.company_notifications  | 2024-11-20 15:22:06.352444
 public.company_notifications  | 2024-11-20 11:18:24.445527
 public.company_notifications  | 2024-11-11 08:19:55.433727
 public.company_notifications  | 2024-10-10 12:43:42.710788
 public.company_notifications  | 2024-10-08 13:37:23.916321
 public.person_notifications   | 2024-11-20 11:15:20.956382
 public.person_notifications   | 2024-10-08 13:37:24.055755
 public.person_notifications   | 2024-11-11 08:15:58.314432
 public.person_notifications   | 2024-10-10 12:39:41.840868
 public.person_notifications   | 2024-11-20 15:19:28.796258

Tried to reset one of MV stats
select mv_activity_reset_stats ('public.company_notifications');
          
	  mv_activity_reset_stats
------------------------------------
 public.company_notifications
 public.company_notifications
 public.company_notifications
 public.company_notifications
 public.company_notifications
(5 rows)

But nothing changed beside reset_last field.

SELECT
mv_stats.mv_name,
mv_stats.create_mv as create_mv, reset_last
FROM mv_stats
order by mv_name;
                   mv_name                   |         create_mv          |         reset_last
---------------------------------------------+----------------------------+----------------------------
 public.company_notifications  | 2024-10-10 12:43:42.710788 | 2024-11-21 08:48:41.964451
 public.company_notifications  | 2024-11-20 11:18:24.445527 | 2024-11-21 08:48:41.964451
 public.company_notifications  | 2024-11-11 08:19:55.433727 | 2024-11-21 08:48:41.964451
 public.company_notifications  | 2024-11-20 15:22:06.352444 | 2024-11-21 08:48:41.964451
 public.company_notifications  | 2024-10-08 13:37:23.916321 | 2024-11-21 08:48:41.964451
 public.person_notifications   | 2024-10-08 13:37:24.055755 |
 public.person_notifications   | 2024-11-20 15:19:28.796258 |
 public.person_notifications   | 2024-10-10 12:39:41.840868 |
 public.person_notifications   | 2024-11-11 08:15:58.314432 |
 public.person_notifications   | 2024-11-20 11:15:20.956382 |

Is that behaviour is normal or not? What to do to eliminate such problem?

**Comment by Simurgl** [comment]
Fixed that by issuing two commands:
truncate _mv_stats;
select  mv_activity_init();

UPD. Looks like this view controlling only direct drop of mat view. Found by our developers.
If mat view has been dropped as part of cascade drop (when some other object dropped with cascade option), then old info retained here. And creating mview again just added new row here. 
Probably this workaround described before would be useful to execute periodically.

**Comment by asotolongo** [comment]
@Simurgl thank you for the report.
yes, the function `mv_activity_reset_stats` works in this way, cleaning the stats 

-  refresh_mv_last= NULL
-  refresh_count= 0
-  refresh_mv_time_last= NULL
-  refresh_mv_time_total= '00:00:00' 
-  refresh_mv_time_min= NULL
-  refresh_mv_time_max= NULL
-  reset_last = timestamp of the moment of the function call

You can clean only the data of your specific MV using `DELETE _mv_stats where mv_name='your_MV'` because `TRUNCATE` will clean all MV data recorded.
